# Generated by Django 4.1.7 on 2023-04-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('preco', models.CharField(max_length=64)),
                ('nome', models.ManyToManyField(blank=True, related_name='itens', to='listas.listas')),
            ],
        ),
    ]
