# Generated by Django 4.1.7 on 2023-04-13 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0002_itens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itens',
            old_name='item',
            new_name='itens',
        ),
        migrations.RenameField(
            model_name='listas',
            old_name='nome',
            new_name='nome_lista',
        ),
        migrations.RemoveField(
            model_name='itens',
            name='nome',
        ),
        migrations.AddField(
            model_name='itens',
            name='nome_lista',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Itens', to='listas.listas'),
            preserve_default=False,
        ),
    ]
